---
groups:
- name: payment-jobs
  jobs:
  - build-payment
  - deploy-payment-to-stage
  - health-check
  - deploy-payment-to-prod
  - execute-payment-load-tests
  - validate-payment-load-test
  - promote-new-version-payment

- name: init-dynatrace
  jobs: 
  - init-dynatrace-payment

resource_types:
- name: dynatrace-resource
  type: docker-image
  source:
    repository: mvilliger/dynatrace-resource

resources:

- name: git-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/sockshop.git

- name: git-jmeter-as-container
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/jmeter-as-container.git

- name: git-payment
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/payment.git

- name: dynatrace
  type: dynatrace-resource
  source:
    apitoken: ((apitoken))
    tenanthost: ((tenanthost))

#- name: payment-image
#  type: docker-image
#  source:
#    repository: ((docker-hub-username))/payment
#    username: ((docker-hub-username))
#    password: ((docker-hub-password))

- name: payment-release-bucket
  type: s3
  source:
    region_name: eu-west-1
    regexp: payment/payment-(.*)
    bucket: ((s3-bucket))
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))

- name: version
  type: semver
  source:
#    driver: s3
#    initial_version: 0.0.1
#    region_name: eu-west-1
#    bucket: ((s3-bucket))
#    access_key_id: ((s3-access-key-id))
#    secret_access_key: ((s3-secret-access-key))
#    key: payment/version
    driver: git
    uri: https://github.com/((workshop-repository))/payment.git
    branch: master
    file: version

# PCF Environments

- name: cf-stage
  type: cf
  source:
    api: ((pcf-stage-api))
    username: ((pcf-stage-deploy-username))
    password: ((pcf-stage-deploy-password))
    organization: ((pcf-stage-organization))
    space: ((pcf-stage-space))
    skip_cert_check: false

- name: cf-production
  type: cf
  source:
    api: ((pcf-prod-api))
    username: ((pcf-prod-deploy-username))
    password: ((pcf-prod-deploy-password))
    organization: ((pcf-prod-organization))
    space: ((pcf-prod-space))
    skip_cert_check: false

jobs:

# Initialize Dynatrace Custom Device

- name: init-dynatrace-payment
  public: true
  plan:
  - aggregate:
    - get: git-pipeline
    - get: git-payment 
  - task: init-dynatrace-task
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/init-dynatrace-task.yml
    params: 
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-payment

# PAYMENT

- name: build-payment
  plan:
  - get: git-payment
    trigger: true  
  - get: version
    params: { pre: rc }
  - task: build-payment-binary
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang, tag: 1.7.1} 
      inputs:
      - name: git-payment
      - name: version
      outputs:
      - name: workspace
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          # output_dir=workspace
          # rm git-payment/Dockerfile
          # cp git-payment/docker/payment/Dockerfile "${output_dir}/Dockerfile"
          # sh git-payment/scripts/build.jb.sh
          # echo "binary to version" > "${output_dir}/payment-$(cat version/number).txt"
          # cp -R git-payment/* "${output_dir}/"
          
          output_dir=workspace
          export WORKDIR=$PWD
          
          cd workspace
          export GOPATH=$PWD
          mkdir -p src/github.com/dynatrace-sockshop/payment/
          cp -R ../git-payment/* src/github.com/dynatrace-sockshop/payment/.
          cd src/github.com/dynatrace-sockshop/payment/
          
          apt-get update
          apt-get install git
          go get -v github.com/Masterminds/glide
          cd $GOPATH/src/github.com/Masterminds/glide
          make build
          export PATH=$PATH:$GOPATH/src/github.com/Masterminds/glide
          
          cd $GOPATH/src/github.com/dynatrace-sockshop/payment/
          glide install && CGO_ENABLED=0 go build -a -installsuffix cgo -o payment main.go
          
          cd $WORKDIR
          cp $GOPATH/src/github.com/dynatrace-sockshop/payment/payment "${output_dir}/"
          mv ${output_dir}/payment ${output_dir}/payment-$(cat version/number)
  - put: payment-release-bucket
    params: 
      file: workspace/payment-*

- name: deploy-payment-to-stage
  serial: true
  public: true
  plan:
  - get: git-payment
    trigger: true
    passed:
      - build-payment
  - get: git-pipeline
    trigger: false      
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      PCF_APP_SUFFIX: ((pcf-stage-payment-suffix)) 
      APP_REPO: git-payment
  - put: dynatrace
    params:
      monspecserviceenvironment: payment/Staging
      pipelinetaskname: deploy-payment-to-stage
      deployversion: v1.0
      APP_REPO: git-payment 
  - put: cf-stage
    params:
      path: git-payment
      manifest: app-manifest-output/manifest.yml 
  
- name: health-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-payment
      trigger: true
      passed:
        - deploy-payment-to-stage
    - get: git-jmeter-as-container
    - get: git-pipeline
  - task: run-load-tests
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/health-test.yml
    params:
      APP_REPO: git-jmeter-as-container
      FUNC_VALIDATION: yes
      PRODUCTION: false
      SCRIPT_NAME: basiccheck.jmx
      PCF_APP_SUFFIX: ((pcf-stage-payment-suffix))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))
      DT_LTN: HealthCheck
      VUCount: 1
      LoopCount: 1

- name: deploy-payment-to-prod
  serial: true
  public: true
  plan:
  - get: git-payment
    trigger: true
    passed:
      - health-check
  - get: git-pipeline
    trigger: false
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-payment-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))              
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-payment-suffix)) 
      APP_REPO: git-payment
      PRODUCTION: true       
  - put: dynatrace
    params:
      monspecserviceenvironment: payment/Production
      pipelinetaskname: deploy-payment-to-prod
      deployversion: v1.0 
      APP_REPO: git-payment      
  - put: cf-production
    params:
      path: git-payment
      manifest: app-manifest-output/manifest.yml 

- name: execute-payment-load-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-payment
      trigger: true
      passed:
        - deploy-payment-to-prod
    - get: git-jmeter-as-container
    - get: git-pipeline
      trigger: false        
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-payment-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))           
  - task: run-load-test
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/load-tests.yml
    params:
      APP_REPO: git-jmeter-as-container
      FUNC_VALIDATION: yes
      PRODUCTION: true
      SCRIPT_NAME: payment_load.jmx
      PCF_APP_SUFFIX: ((pcf-prod-payment-suffix))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))
      DT_LTN: LoadTest
      VUCount: 5
      LoopCount: 20   
  - task: push-dynatrace-monspec-data
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/push-dynatrace-monspec-data.yml
    params: 
      monspecserviceenvironment: payment/Production-$NEXT_APP_COLOR
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-payment   

- name: validate-payment-load-test
  serial: true
  public: true
  plan:
  - get: git-payment
    trigger: true
    passed:
      - execute-payment-load-tests
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-payment-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))       
  - task: validate-via-monspec
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/validate-via-monspec.yml
    params: 
      monspeccomparison: payment/Production-$NEXT_APP_COLOR\ToProduction-$CURRENT_APP_COLOR\Last5m
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-payment     

- name: promote-new-version-payment
  serial: true
  public: true
  plan:
  - get: git-payment
    trigger: true
    passed:
      - validate-payment-load-test
  - get: version
    params: { bump: patch }
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-payment-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))   
  - task: switch-app-routes
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/update-routes.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-payment-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))              
#  - put: version
#    params: { file: version/number }